spring:
  application:
    name: PakGoPay
  rabbitmq:
    host: 8.148.79.164
    port: 5672
    username: zf
    password: zf@qwe.123
  redis:
    host: 8.148.79.164
    port: 6379
    password: zf@qwe.123
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://8.148.79.164:3306/localdev?characterEncoding=UTF8&useSSL=false&serverTimezone=UTC&keepAlive=true
    username: root
    password: zf.qwe.123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 60000
      idle-timeout: 60000
      max-lifetime: 300000



server:
  address: localhost
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/*.xml