spring:
  application:
    name: PakGoPay
  rabbitmq:
    host: 8.148.79.164
    port: 5672
    username: zf
    password: "ENC(LZ1Qu4FShlsHvVLzs/xYiUh1hUbdKBYu5wk9tMIEKffl9PN5hW1cB34KO44ayEAP)"
  data:
    redis:
      host: 8.148.79.164
      port: 6379
      password: "ENC(erE+8wtM9HSF+WK5hWQq6dT1vnp2FzwWkb8Xd4OGl7OVGZbqiTjAc2mtMBddHr0M)"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://8.148.79.164:5432/test
    username: postgres
    password: "ENC(l6y1wvjXUYFFgnYHhl0zi7y5tJTprEwjpQ5uQBl8hfm0uSQHWeSnTlOWINqwYPcU)"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 1000
      idle-timeout: 60000
      max-lifetime: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
server:
  address: localhost
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/*.xml
turnstile:
  enabled: true
  secret: ${TURNSTILE_SECRET:}
  verify-url: https://challenges.cloudflare.com/turnstile/v0/siteverify
pakgopay:
  cloudflare:
    apiToken: ENC(uQnD8BqKnGKfVYhNyDHStCpmbTFxducJZSNRKYFpcqyN6IuaB8nJC/GLV4vnzIpBAemp2ciNQsiiU7atVtMFRwCQnflC5vFVnNzVP5RbiII=)
    zoneId: 1b5b29d8df1d0f084a28393d5c7032ed