spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: PakGoPay
  rabbitmq:
    host: 8.148.79.164
    port: 5672
    username: zf
    password: zf@qwe.123
  data:
    redis:
      host: 8.148.79.164
      port: 6379
      password: zf@qwe.123
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://8.148.79.164:5432/test
    username: postgres
    password: zf.qwe.123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 1000
      idle-timeout: 60000
      max-lifetime: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  address: 0.0.0.0
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
