spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: PakGoPay
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: "ENC(sYYbVn+QvpMiw/NJQ40Fy181liOzDn9+X0kySN/Qcz8rxyeav3Da38MhZFVy5kAZ)"
  data:
    redis:
      host: 8.148.79.164
      port: 6379
      password: "ENC(EPgW2Mhg0y/Ltc+t9mBzSmmA11iYzJRiJ1nXFHxcvcYFopCZELpL9msQd0VMT2su)"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://8.148.79.164:5432/test
    username: postgres
    password: "ENC(41ElKO22DHN/IsrZG0tkdLj+x9zSDEJ3aSNhpAhJubZ60NdqKr4/u5ypoTBZk/BR)"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 1000
      idle-timeout: 60000
      max-lifetime: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
server:
  address: 0.0.0.0
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
turnstile:
  enabled: false
  secret: 0x4AAAAAACYPbxWws6CC8f1U0AZShnoQOY0
  verify-url: https://challenges.cloudflare.com/turnstile/v0/siteverify
