spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: PakGoPay
  rabbitmq:
    host: pakgopay-rabbitmq
    port: 5672
    username: xiaoyou
    password: "ENC(IyYEbQuxanXY0fTveLB9SKrjo8Ulk8Swwrr8VbuP0fBW/q23FJIT501PxB+MJzr6)"
  data:
    redis:
      host: pakgopay-redis
      port: 6379
      password: "ENC(b5hhW1348eyAF5C2OK7IxiXMXpcMfdzX4IR1WjBI1itCZfl532XYCH0O3/IIZa88)"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://pgm-gs54h1z25sz4mftjdo.pgsql.singapore.rds.aliyuncs.com:5432/test
    username: xiaoyou
    password: "ENC(Ey/mtoNnV5MkLjfGhyUqtOWQPIIsCpgHB9VM6031gqfGcqHZEYkVoPnIh86U+iS7)"
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 1000
      idle-timeout: 60000
      max-lifetime: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
server:
  address: 0.0.0.0
  port: 8090
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
turnstile:
  enabled: true
  secret: ${TURNSTILE_SECRET:}
  verify-url: https://challenges.cloudflare.com/turnstile/v0/siteverify
pakgopay:
  cloudflare:
    apiToken: ENC(uQnD8BqKnGKfVYhNyDHStCpmbTFxducJZSNRKYFpcqyN6IuaB8nJC/GLV4vnzIpBAemp2ciNQsiiU7atVtMFRwCQnflC5vFVnNzVP5RbiII=)
    zoneId: 1b5b29d8df1d0f084a28393d5c7032ed
  rate-limit:
    enabled: false
